### ISSUE TITLE
Production prices

### ISSUE THREAD

**Issue by ThatIsAUsername** [ThislsAUsername/DefendPeace#115]
Are missing. I want to see how much units cost when I go to build them. This worked before.

Extra credit: grey out (or remove?) options that are out of the Commander's price range.
Extra Extra credit: Add unit icons to the production menu.

**Comment by ThislsAUsername** [comment]
I feel like this would be a change to the UnitModel's toString()?
Doing weird magic in the view could be a thing, I guess.

**Comment by ThislsAUsername** [comment]
Nevermind. SelectUnitProduction() should use strings instead of Models.
The logic to format everything is all dead code in InGameProductionMenu.
