### ISSUE TITLE
AIs can create valid but conflicting GameActions that fail to execute without being detected.

### ISSUE THREAD

**Issue by ThatIsAUsername** [ThislsAUsername/DefendPeace#136]
Probably related to #26 and #73.
An AI can create two move actions for different units to move to the same place, or two attack actions for the same unit. Despite giving invalid moves, MapController doesn't end the AI's turn. I'd like to better vet these conditions.
Tentatively, we could move GameAction validation into the call to get events. Have to look into it more though.

**Comment by ThislsAUsername** [comment]
Another fun instance of a similar issue: an AI can queue more than one capture event for the same infantry, then actually succeed in capturing twice in one turn.

Reproduction steps: branch cmdrAve or downstream, Firing Range, P1 as ISAI
Turn 2, a fresh infantry will capture in one turn.

**Comment by ThislsAUsername** [comment]
I think this issue is OBE at this point, yeah?

**Comment by ThatIsAUsername** [comment]
I assume so, though we should probably verify that your repro steps don't work anymore.

**Comment by ThislsAUsername** [comment]
Duly verified.
