### ISSUE TITLE
Weather Priority

### ISSUE THREAD

**Issue by ThislsAUsername** [ThislsAUsername/DefendPeace#179]
When setting the weather forecast, it should be possible to specify a strength/priority level for the weather in question.
If the priority/strength is not greater than or equal to the current weather's strength, it should be ignored.

Possibly also allow adding a sequence of weather/priority pairs, with negative priorities not changing the weather from its current state.

**Comment by ThatIsAUsername** [comment]
I would advocate a two-priority system. Either it can replace the current weather, or it can't. No "degrees of weather strength".
So non-preemptive weather changes (e.g. d2d random weather) would only take effect if the current weather is non-preemptive, and preemptive changes (typically just CO-initiated changes) would take effect regardless.

**Comment by ThislsAUsername** [comment]
Sure, but that means the weather could just oscillate forever between two states, with neither Commander feeling any effect at all.
It makes more sense, IMO, to make strength granular so that two hypothetical (opposed) weather-based D2Ds could actually affect each other without just targeting different areas of the board.

It also makes some amount of sense for Abilities; Olaf vs Drake would feel pretty stupid if neither of them had mass damage, since whoever used a power first would have quite possibly no affect on the other CO.

**Comment by ThatIsAUsername** [comment]
> Sure, but that means the weather could just oscillate forever between two states, with neither Commander feeling any effect at all.

If they both have Ave-esque init-turn-refresh on their weather effects, then maybe. If nothing else, it would still give the defender a bit of an advantage (for Ave, at least).

> It also makes some amount of sense for Abilities; Olaf vs Drake would feel pretty stupid if neither of them had mass damage, since whoever used a power first would have quite possibly no affect on the other CO.

Only if they both get their CO power at the same time. Which could create an interesting dynamic of trying to bait the other guy's into using his ability first.

In your scheme, how is this resolved? Do we just decide that Olaf's snow overpowers Drake's rain, and Drake is just SOL? I like that even less.

**Comment by ThislsAUsername** [comment]
> If they both have Ave-esque init-turn-refresh on their weather effects, then maybe. If nothing else, it would still give the defender a bit of an advantage (for Ave, at least).

That's fair. It'd probably be best for any and all weather-affecting-D2D COs to have different fields of effect anyway.

> Only if they both get their CO power at the same time. Which could create an interesting dynamic of trying to bait the other guy's into using his ability first.

IMO it's not interesting at all, unless the power has some sort of utility that could reasonably give you the edge even though your weather will be canceled.
It'd be kind of like a Hawke ditto: whoever SCOPs first loses (except less extreme).

Another Hawke problem is Sonja's Counter Break. You might assume that Counter Break would counter Counter Break, resulting in normal combat if two Sonjas SCOP at each other... but that's not the case in the games, and I think it's actually better that way.
If Counter Break counters Counter Break, then the first Sonja to use her power gets basically no value from it, and has to deal with the full might of the opposing Counter Break on her next turn. In the actual scenario, each Sonja can use Counter Break to full effect without worrying that it will just be nullified by something outside of their control.

> In your scheme, how is this resolved? Do we just decide that Olaf's snow overpowers Drake's rain, and Drake is just SOL? I like that even less.

It gives us a new knob to turn.

I'd put forth two possible cases:
Say Olaf gets precedence. That's fine, but snow is *also* more crippling than rain (in 90% of cases). That gives you a pretty good case for making Drake's ability significantly cheaper, which gives him initiative.

Say Drake gets precedence. Let's say we call rain with precedence vs snow with less is equal value... we still are better than when we started, because Drake still has initiative: he can drop rain with impunity, and then Olaf gets to use his Snow without fear of reprisal.

I like both of these interactions better than Hawke-style first-person-to-COP-loses.

Also also, the equal-or-greater logic fully allows for the original style, since everyone at priority X will overwrite on their own turn.

**Comment by ThatIsAUsername** [comment]
>You might assume that Counter Break would counter Counter Break, resulting in normal combat if two Sonjas SCOP at each other... 

Nope - the ability is stated to allow "stronger counterattacks" - no reason for one to prevent the other.

> It gives us a new knob to turn.

I don't think more knobs is always better - Do we have to include the "strength" of each weather power in its description? Users aren't going to want to worry about whether their power has enough strength to work in a given situation. You might have a scheme that feels logical, but it would be confusing for someone who doesn't sit down and figure out "weather precedence" before trying to use an ability.

Besides the added mental overhead for users, it would deny options to players. Say Drake has precedence over Olaf, and starts the rain. Olaf's best option (probably) is to fire his own COP, get the attack boost to buff his wounded units, and strike back hard (the likely alternative being a full retreat for that turn). But his COP wouldn't even stop the rain.
If we allow last-weather-condition-wins, then both players would get most of their utility. Drake would have the rain during his turn, and Olaf would get snow during his. The weather would reset for both of them by their next turns anyway.
```
Last-Weather-Wins:
Cmdr    : D O D O
Use COP : * *
Turn    : 1 2 3 4
Weather : R S S C

Drake has Priority:
Cmdr    : D O D O
Use COP : * *
Turn    : 1 2 3 4
Weather : R R S C
```
LWW Drake loses very little from popping his COP first. The weather would be snow when his turn next rolled around either way. The biggest difference is that he doesn't force Olaf to wade through rain for a turn, but a charged Olaf shouldn't have to deal with weather he doesn't like.
DHP Olaf, on the other hand, loses out big time if his power is declawed due to Drake firing first, and then we have upset users quite reasonably reporting a bug since Olaf's power failed to bring the snow.

**Comment by ThislsAUsername** [comment]
> > You might assume that Counter Break would counter Counter Break, resulting in normal combat if two Sonjas SCOP at each other...
> 
> Nope - the ability is stated to allow "stronger counterattacks" - no reason for one to prevent the other.

Huh, I hadn't noticed that. Either way, it's mechanically just firststrike on defense, which you can figure out pretty easily by playing the game.
IMO just saying "stronger counterattacks" is kind of misleading, since it actually reduces the opponent's expected damage by a lot (and the UI doesn't indicate that at all, unlike in our game).

> > It gives us a new knob to turn.
> 
> I don't think more knobs is always better - Do we have to include the "strength" of each weather power in its description? Users aren't going to want to worry about whether their power has enough strength to work in a given situation. You might have a scheme that feels logical, but it would be confusing for someone who doesn't sit down and figure out "weather precedence" before trying to use an ability.

Hmm. You're definitely correct here, though my thinking was that weather precedence would scale with whatever logic the power used to generate the weather in the first place; there probably shouldn't be global weather powers and if there were, it would be sensible to include something about how strong it is. (Since it's just a global change with no internal mechanics, a little extra detail isn't overkill IMO.)

> Besides the added mental overhead for users, it would deny options to players. Say Drake has precedence over Olaf, and starts the rain. Olaf's best option (probably) is to fire his own COP, get the attack boost to buff his wounded units, and strike back hard (the likely alternative being a full retreat for that turn). But his COP wouldn't even stop the rain.

The generic boost is +10 attack and +10 defense. Olaf will (statistically) get much much more mileage out of that boost if he waits until Drake is no longer benefiting from the defense, because of how defense scales.
So yes, his best option is a full retreat, most likely.
Also, this can be *good* for Olaf. If Drake uses his power first (which he has an incentive to do, since Olaf cannot nullify his weather), it means Olaf gets to affect Drake with *his* weather unopposed.

> If we allow last-weather-condition-wins, then both players would get most of their utility. Drake would have the rain during his turn, and Olaf would get snow during his. The weather would reset for both of them by their next turns anyway.

Olaf doesn't get any benefit from his snow, though. It's no different to him than Clear... and Drake is the same way with Rain. The real benefit for Olaf is that he doesn't have to deal with rain... but that effectively nullifies Drake's power.
The benefit Drake *really* wants from his power is to make Olaf wade through rain (which he can't have in LWW); if he just wanted the generic +10/10, he'd be playing Adder (in this hypothetical scenario where Drake is not a mass damage CO, obviously).

> ```
> Last-Weather-Wins:
> Cmdr    : D O D O
> Use COP : * *
> Turn    : 1 2 3 4
> Weather : R S S C
> 
> Drake has Priority:
> Cmdr    : D O D O
> Use COP : * *
> Turn    : 1 2 3 4
> Weather : R R S C
> ```
> 
> LWW Drake loses very little from popping his COP first. The weather would be snow when his turn next rolled around either way. The biggest difference is that he doesn't force Olaf to wade through rain for a turn, but a charged Olaf shouldn't have to deal with weather he doesn't like.
> DHP Olaf, on the other hand, loses out big time if his power is declawed due to Drake firing first, and then we have upset users quite reasonably reporting a bug since Olaf's power failed to bring the snow.

LWW Drake does lose a lot from popping his COP first: namely, Olaf doesn't have to deal with rain.
I don't strictly agree that a charged Olaf shouldn't need to care about existing battle conditions; the fact that Drake and Olaf's powers aren't at all situational makes them horrible to fight against in the carts, and is IMO a significant issue with their design.

Honestly, it was a poor choice on my part to use Drake and Olaf as the example here. They have established behaviors (and global weather), and users would expect them to act a certain way. (They also have other aspects, namely mass damage, that color the comparison.)

**Comment by ThatIsAUsername** [comment]
> IMO just saying "stronger counterattacks" is kind of misleading

True, but even if we amend the description to "Counterattacks before the attacker when defending" There's nothing there to imply that two users of Counter-break would counter each other. They would just both attack second when attacking, which is exactly what that description promises. This feels tangential to the weather discussion though.

> weather precedence would scale with whatever logic the power used to generate the weather in the first place; there probably shouldn't be global weather powers and if there were, it would be sensible to include something about how strong it is. 

The incredible vagueness in this paragraph is terrifying, from both the developer and user-experience perspectives. The one clear detail (adding some indicator of weather strength) was an example I gave of something the user wouldn't want to have to deal with, and that wouldn't be remotely intuitive (not t mention that past familiarity with AW would just make the confusion worse).

> Also, this can be good for Olaf. If Drake uses his power first (which he has an incentive to do, since Olaf cannot nullify his weather), it means Olaf gets to affect Drake with his weather unopposed.

Strongly disagree. Olaf can easily wait to use his power in LWW too; in DHP he *has to* wait - it reduces his strategic options. Plus, getting hammered by Drake's power and being in full retreat for a turn, he may have lost enough ground that it doesn't make sense to use his ability again.

> The benefit Drake really wants from his power is to make Olaf wade through rain (which he can't have in LWW)

Hmm, yes and no. I mean, he still gets the 10/10 bonus. He would lose out on making Olaf wade through rain, but it's a far cry from "first to COP loses" as you cast it to be. Not to mention that (in LWW) this could force Olaf to pop his COP too (at a time when--as you point out--he may get less combat utility), just to mitigate the effects of the rain. With DHP, Olaf doesn't have to make that choice, so Drake can't try to force Olaf's COP in disadvantageous circumstances.

> Honestly, it was a poor choice on my part to use Drake and Olaf as the example here... (They also have other aspects, namely mass damage, that color the comparison.)

Right, and this will just get more complicated as we add more weather-based commanders. Using simple rules with no complex mechanics is our best bet to maintain sanity (both for ourselves and our users).

> They have established behaviors (and global weather), and users would expect them to act a certain way.

This is key; strategic considerations aside, from a user-experience perspective it would be awful to have Olaf's COP not result in snow.

**Comment by ThislsAUsername** [comment]
> > weather precedence would scale with whatever logic the power used to generate the weather in the first place; there probably shouldn't be global weather powers and if there were, it would be sensible to include something about how strong it is.
> 
> The incredible vagueness in this paragraph is terrifying, from both the developer and user-experience perspectives. The one clear detail (adding some indicator of weather strength) was an example I gave of something the user wouldn't want to have to deal with, and wouldn't know to look for (especially if they have past familiarity with AW and think they know the rules).

It's vague, but different COs are liable to have different mechanics. I guess it's fair to say that not all will be so granular as Ave is, though. (and looking at my stable of related concepts bears that out)
The weather strength would be included in the CO info, which the player would have to look at to know what to expect in the first place... assuming we didn't bring in somebody like Olaf who they already understand.

> That does color the comparison... and this will just get more complicated as we add more weather-based commanders. Using simple rules with no complex mechanics is our best bet to maintain sanity (both for ourselves and our users).

I suppose simplicity is a fairly telling argument.
Combined with your other points, I guess I'm willing to concede.

However, I'm not convinced, at this point, that there should be any weather that *doesn't* override.
Random weather, if/when we add it, would heavily alter the game in a lot of ways anyhow, so its affects messing up Ave's snowy playpen doesn't really bother me.
I guess you could add non-overriding weather as part of a D2D, but that would be weird.

**Comment by ThatIsAUsername** [comment]
> However, I'm not convinced, at this point, that there should be any weather that doesn't override.

In that case... does this issue just go away? Problem solved!

**Comment by ThislsAUsername** [comment]
> In that case... does this issue just go away? Problem solved!

Perfect! We now have the ability to solve any issue: just argue about it until nobody wants it anymore.
