### ISSUE TITLE
Reduce validation duplication in GameActions

### ISSUE THREAD

**Issue by ThislsAUsername** [ThislsAUsername/DefendPeace#198]
I would add a `shouldPreempt()` function to `MoveAction` and base some or all of the other action types off of it.
This may or may not be worth doing, but I'm recording it in the issue list so we don't forget.

**Comment by ThatIsAUsername** [comment]
My main concern here is that `shouldPreempt()` or `wasPreempted()` or whatever can only be evaluated at event-generation time with a `MapMaster`.
I mean, I guess you could implement it to always return false until `getEvents()` had been called, and then compare the zeroth event's endpoint with `getMoveLocation()`. It would probably have to be private though.

**Comment by ThislsAUsername** [comment]
I think this is OBE, seeing as actions generate their events in `getEvents()`

**Comment by ThatIsAUsername** [comment]
I think I'm fine with that.
