### ISSUE TITLE
Turn init fixes

### ISSUE THREAD

**Issue by ThislsAUsername** [ThislsAUsername/DefendPeace#229]
When air/sea units run out of fuel, they don't die. That's a little weird.
Needs either a way to determine if you're gonna be supplied by another unit (hard) or a way to animate/execute two batches of events on turn init

A related issue that might help with the fix is that turn init functions actually affect game state - ideally, they should return GameEvents to do the same actions.

**Comment by ThatIsAUsername** [comment]
Alternatively, we could copy the source material, and if they are out of fuel they die even if a refueling unit is adjacent.
I'm fine with allowing them to live, though.

**Comment by ThislsAUsername** [comment]
I don't really care whether they die next to APCs or not; I just want the results to be consistent and ideally not show a unit that's about to blow up being refueled.
