### ISSUE TITLE
Victory/Defeat panels are badly placed when in fullscreen

### ISSUE THREAD

**Issue by ThatIsAUsername** [ThislsAUsername/DefendPeace#295]
CO face seems to be positioned about right, but the text is invisible off the side, and the secondary bar is lost below the map too.

**Comment by ThislsAUsername** [comment]
Looks fine to me, boss.
![Screenshot from 2020-05-31 04-30-21](https://user-images.githubusercontent.com/8674241/89737928-93273500-da3a-11ea-925c-fc503f881263.png)

**Comment by ThislsAUsername** [comment]
Hmm. Seems to only reproduce if you're maximized before the victory/defeat.
Probably has to do with using window dimensions instead of map dimensions.

Also, allied victory isn't a thing, apparently.
