### ISSUE TITLE
Assess return values of `Utils.findShortestPath`

### ISSUE THREAD

**Issue by ThatIsAUsername** [ThislsAUsername/DefendPeace#366]
It can currently return either `null` or a zero-length `Path` to indicate that it could not find a destination. Is there a distinction between these results meaningful enough to justify separate failure modes, or can we simplify?

**Comment by ThislsAUsername** [comment]
It seems the distinction is "`null` means the inputs are unusable; empty means your inputs are valid but there's no solution"

That's not a terribly clean dividing line, and I'm not sure there's any reason to use such a line. I think it's probably fair to just output `null` for all no-solution cases?

**Comment by ThatIsAUsername** [comment]
Sounds sensible to me.

**Comment by ThislsAUsername** [comment]
Fixed by #395, probably earlier
