### ISSUE TITLE
Capture defeat should grant all properties to the capturer

### ISSUE THREAD

**Issue by ThislsAUsername** [ThislsAUsername/DefendPeace#88]
I suggest this be implemented by adding a "capturing CO" argument to the CommanderDefeatEvent.
This would be null on defeat by rout.

**Comment by ThatIsAUsername** [comment]
Hah, Issue #59 is the same as this one. Except you closed it.
I'm not opposed to implementing this though, especially since it's a pretty rare case, and I approve of rewarding finesse.

**Comment by ThislsAUsername** [comment]
That was a long time ago, and I have a short memory.
